version: "3.8"
services:
  dbb25:
    container_name: dbb25
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=
    ports:
      - 3308:3306
      
  app:
    depends_on:
      - dbb25
    restart: always
    build: .
    ports:
      - 8081:8023